<?php

require('fpdf/fpdf.php');
require_once('../protected/controlUnit.php');

logged();

$h=0.47; 
$f=8;
$w=0.73;

//$tmH = ($h*50)+($h*mysqli_num_rows($Matricl));

$pdf=new FPDF('P','cm',array(21.59,35,56));
$pdf->SetMargins(0.7, 0.6, 0.7);
$pdf->SetAutoPageBreak(true,0.1); 
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->Cell(10, 1, '', 0);
$pdf->SetFont('Arial', 'bu', 12);
$pdf->Cell(0, 0, utf8_decode("MATRICULA INICIAL (Regimen Regular)"), 0,0,'R');
$pdf->Ln(0.2);
$pdf->Cell(11.5, 1, '', 0);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(5, 0.5, utf8_decode('Código del formato:'), 0,0,'R');
$pdf->Cell(3, 0.5, 'RR-DEA-01-03', 0);
$pdf->Ln(1);
$pdf->Cell(11.85, 0.1, '', 0);
$pdf->SetFont('Arial', 'b', 10);
$pdf->Cell(3, $h, utf8_decode('I. Año Escolar:'), 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, $h,anoEscpdf($ae['idAnoEscolar']), 'B',0);
$pdf->Ln(0.5);
$pdf->Cell(12.15, 0.1, '', 0);
$pdf->SetFont('Arial', 'b', 10);
$pdf->Cell(4.5,$h, utf8_decode('Mes y año de la matricula:'), 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, $h, date('m-Y'), 'B');
$pdf->Ln(0.8);
$pdf->SetFont('Arial', 'b', 10);
$pdf->Cell(2.5, $h, 'II. Datos del Plantel', 0);
$pdf->Ln(0.4);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(2.7, $h, utf8_decode('Cód. Plantel:'), 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(2, $h,$dtPlantel['codigoDEA'], 'B',0,'B');
$pdf->Cell(0.2, $h,'', 0,0,0);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(1.5, $h, 'Nombre:', 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(10, $h, $dtPlantel['nombrePlant'], 'B',0,'B');
$pdf->Cell(.2, $h,'', 0,0,0);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(1.8, $h, 'Dtto. Esc:', 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(0,$h,$dtPlantel['distritoEscolarPlant'], 'B');
$pdf->Ln(.5);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(1.6, $h, utf8_decode("Dirección:"), 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(11.68, $h, $dtPlantel['direccPlantel'],'B');
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(1.8, $h, utf8_decode('Teléfono:'), 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(0, $h, $dtPlantel['telefonoPlant'], 'B');
$pdf->Ln(.5);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(1.46, $h, 'Municipio:', 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(0.2, $h,'', 0,0,0);
$pdf->Cell(5.11, $h, $dtPlantel['municipioPlant'], 'B');
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(0.2, $h,'', 0,0,0);
$pdf->Cell(2, $h, 'Ent. Federal:', 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(3.75, $h, idtfEntFedpdf($dtPlantel['idEntidaFederal']), 'B');
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(2.35, $h, 'Zona Educativa:', 0);
$pdf->SetFont('Arial', '',$f);
$pdf->Cell(0, $h, utf8_decode($dtPlantel['zonaEducativaPlant']),'B');
$pdf->Ln(.8);
$pdf->SetFont('Arial', 'b', 10);
$pdf->Cell(5.2, $h, utf8_decode('III. Identificación del Curso:'), 0);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(2.5, $h, 'Plan de estudio:', 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(0, $h,utf8_decode(Planpdf($_GET['idGrad'])), 'B');
$pdf->Ln($h);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(1.23, $h, utf8_decode('Código:'), 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(2.2, $h, codPlanpdf($_GET['idGrad']),'B');
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(0.2, $h,'', 0,0,0);
$pdf->Cell(1.6, $h, utf8_decode('Mención:'), 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(0, $h, mencpdf($_GET['idGrad']), 'B');
$pdf->ln(.5);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(2, $h, utf8_decode('Grado o Año:'), 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(1.4, $h,utf8_decode($_GET['idGrad'].'º'), 'B',0,'C');
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(1.5, $h, utf8_decode('Sección:'), 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(1.4, $h,'"'.seccnpdf($_GET['idSecc']).'"', 'B',0,'C');
$pdf->Cell(0.2, $h,'', 0,0,0);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(4.6, $h, utf8_decode('Nº de Alumnos de la Sección:'), 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(1.3, $h, mysqli_num_rows($Matricl), 'B',0,'C');
$pdf->Cell(1.2, $h,'', 0,0,0);
$pdf->SetFont('Arial', 'b', $f);
$pdf->Cell(4.3, $h, utf8_decode('Nº de Alumnos en esta Página:'), 0);
$pdf->SetFont('Arial', '', $f);
$pdf->Cell(0, $h, ' '/*variable alumno_pag*/, 'B');
$pdf->Ln($h*2);
$pdf->SetFont('Arial', 'b', 10);
$pdf->Cell(0, $h, utf8_decode('IV. Datos de la Identificación del Alumno'), 0);
$pdf->Ln($h);
$pdf->SetFont('Arial', 'B', $f);
$pdf->Cell(.73, $h*2, utf8_decode('Nº'), 1,0,'C');
$pdf->Cell(2.93, $h*2, 'Cedula de Identidad', 'TBR',0,'C');
$pdf->Cell(5.11, $h*2, 'Apellidos', 'TBR',0,'C');
$pdf->Cell(5.11, $h*2, 'Nombres', 'TBR',0,'C');
$pdf->Cell(.85, $h*2, 'Sexo', 'TBR',0,'C');
$pdf->Cell(2.35, $h, 'Fecha de Nacim.', 'TBR',0,'C');
$pdf->Cell(3.1, $h, 'Escolaridad', 'TBR',0,'C');
$pdf->Ln($h);
$pdf->Cell(14.73, $h, '', 0);
$pdf->Cell(.783, $h, utf8_decode('Día'), 'BTR',0,'C');
$pdf->Cell(.783, $h, 'Mes', 'BTR',0,'C');
$pdf->Cell(.783, $h, utf8_decode('Año'), 'BTR',0,'C');
$pdf->Cell(0.775, $h, 'RG', 'BTR',0,'C');
$pdf->Cell(0.775, $h, 'RP', 'BTR',0,'C');
$pdf->Cell(0.775, $h, 'MP', 'BTR',0,'C');
$pdf->Cell(0.775, $h, 'DI', 'BTR',0,'C');
$pdf->SetFont('Arial', '', $f);
$pdf->Ln($h);
//---------------------------------listado de estudiante
//if(==){

	$num=0;
	$nList=mysqli_num_rows($Matricl);
	while($dtMatricl = mysqli_fetch_array($Matricl)){
		$num ++;
		$RG='';
		$RP='';
		$MP='';
		$DI='';

  		$dtEst=tbArray(consultEstud($dtMatricl['ciEstudiante']));
		
		$pdf->Cell(.73, $h, $num, 'BLR');
		$pdf->Cell(2.93, $h,$dtMatricl['ciEstudiante'], 'BR');
		$pdf->Cell(5.11, $h,$dtEst['apellidosEst'], 'BR');
		$pdf->Cell(5.11, $h,$dtEst['nombresEst'], 'BR');
		$pdf->Cell(.85, $h, sexpdf($dtMatricl['ciEstudiante']), 'BR',0,'C');
		$pdf->Cell(.783, $h, diapdf($dtMatricl['ciEstudiante']),'BR',0,'C');
		$pdf->Cell(.783, $h, mespdf($dtMatricl['ciEstudiante']), 'BR',0,'C');
		$pdf->Cell(.783, $h, anopdf($dtMatricl['ciEstudiante']), 'BR',0,'C');
			if($dtMatricl['idEscolaridad']==1){	$RG = 'X'; }
			else{if($dtMatricl['idEscolaridad']==2){	$RP = 'X'; }
			else{if($dtMatricl['idEscolaridad']==3){	$MP = 'X'; }
			else{if($dtMatricl['idEscolaridad']==4){	$DI = 'X'; }}}}
			$pdf->Cell(0.775, $h, $RG, 'BR',0,'C');
			$pdf->Cell(0.775, $h, $RP, 'BR',0,'C');
			$pdf->Cell(0.775, $h, $MP, 'BR',0,'C');
			$pdf->Cell(0.775, $h, $DI, 'BR',0,'C');
		$pdf->Ln($h);
	}
	
for($i=0;$i!=(30-$nList);$i++){	
$num++;
	$pdf->Cell(.73, $h, $num, 'BLR');
	$pdf->Cell(2.93, $h,'', 'BR');
	$pdf->Cell(5.11, $h,'', 'BR');
	$pdf->Cell(5.11, $h,'', 'BR');
	$pdf->Cell(.85, $h, '', 'BR',0,'C');
	$pdf->Cell(.783, $h, '','BR',0,'C');
	$pdf->Cell(.783, $h, '', 'BR',0,'C');
	$pdf->Cell(.783, $h, '', 'BR',0,'C');
	$pdf->Cell(0.775, $h, '', 'BR',0,'C');
	$pdf->Cell(0.775, $h, '', 'BR',0,'C');
	$pdf->Cell(0.775, $h, '', 'BR',0,'C');
	$pdf->Cell(0.775, $h, '', 'BR',0,'C');
	$pdf->Ln($h);
}


$pdf->Ln($h);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(0, $h, 'V. Observaciones', 0);
$pdf->Ln($h);
$pdf->SetFont('Arial', '', 9);
$pdf->Cell(0, $h-.20, '', 'TLR');
$pdf->Ln($h-.20);
$pdf->MultiCell(0, $h, Observ($dt), 'LR');
$pdf->Ln(0);
$pdf->Cell(0, $h-.20, '', 'BLR');
$pdf->Ln($h*2);
$pdf->SetFont('Arial', 'b', 10);
$pdf->Cell($w*6, $h,utf8_decode('VI. Fecha de Remisión'), 1);
$pdf->Cell($w*6, $h, '', 1);
$pdf->Cell($w*2, $h, '', 0);
$pdf->Cell($w*7, $h, utf8_decode('VII. Fecha de Recepción'), 1);
$pdf->Cell(0, $h, '', 1);
$pdf->Ln($h);
$pdf->Cell($w*6, $h, 'Director(a)', 'BRL',0,'C');
$pdf->Cell($w*6, $h, '', 'R');
$pdf->Cell($w*2, $h, '', 0);
$pdf->Cell($w*7, $h, 'Funcionario Receptor', 'BRL',0,'C');
$pdf->Cell(0, $h, '', 'R');
$pdf->Ln($h);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell($w*6, $h, 'Apellidos y Nombres:', 'BRL');
$pdf->Cell($w*6, $h, '', 'R');
$pdf->Cell($w*2, $h, '', 0);
$pdf->Cell($w*7, $h, 'Apellidos y Nombres:', 'BRL');
$pdf->Cell(0, $h, '', 'R');
$pdf->Ln($h);
$pdf->Cell($w*6, $h*2, '1', 'RL',0,'C');
$pdf->Cell($w*6, $h*2, '', 'R');
$pdf->Cell($w*2, $h*2, '', 0);
$pdf->Cell($w*7, $h*2, '', 'RL');
$pdf->Cell(0, $h*2, '', 'R');
$pdf->Ln($h*2);
$pdf->SetFont('Arial', '', 9);
$pdf->Cell($w*6, $h, utf8_decode('Número de Cédula Identidad'), '1');
$pdf->SetFont('Arial', 'b', 10);
$pdf->Cell($w*6, $h, 'Sello del Plantel', 'R',0,'C');
$pdf->Cell($w*2, $h, '', 0);
$pdf->SetFont('Arial', '', 9);
$pdf->Cell($w*7, $h, utf8_decode('Número de Cédula Identidad'), '1');
$pdf->SetFont('Arial', 'b', 9);
$pdf->Cell(0, $h,'Sello de la Zona Educativa', 'R',0,'C');
$pdf->Ln($h);
$pdf->Cell($w*6, $h*2, '1', '1',0,'C');
$pdf->Cell($w*6, $h*2, '', 'R');
$pdf->Cell($w*2, $h*2, '', 0);
$pdf->Cell($w*7, $h*2, '', '1');
$pdf->Cell(0, $h*2,'', 'R');
$pdf->Ln($h*2);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell($w*6, $h, 'Firma:', '1');
$pdf->Cell($w*6, $h, '', 'R');
$pdf->Cell($w*2, $h, '', 0);
$pdf->Cell($w*7, $h,'Firma:', '1');
$pdf->Cell(0, $h,'', 'R');
$pdf->Ln($h);
$pdf->Cell($w*6, $h*2, '', '1');
$pdf->Cell($w*6, $h*2, '', 'R,B');
$pdf->Cell($w*2, $h*2, '', 0);
$pdf->Cell($w*7, $h*2, '', '1');
$pdf->Cell(0, $h*2,'', 'R,B');
$pdf->Ln($h);
$pdf->Ln($h);
ob_end_clean();
$pdf->Output('Matricula Inicial'.$_GET['idGrad'].'-'.$_GET['idSecc'].'.pdf','I');
?>